[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions.generate-response]
  included_files = ["node_modules/openai/**"]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8888
  publish = "."
  autoLaunch = true