[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions.generate-response]
  included_files = ["node_modules/openai/**"]
  timeout = 30

[functions.send-newsletter]
  included_files = ["node_modules/nodemailer/**"]
  timeout = 30

# Add these redirect rules at the top of your redirects section
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://lukaskubiena.com/*"
  to = "https://lukaskubiena.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.lukaskubiena.com/*"
  to = "https://lukaskubiena.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.lukaskubiena.com/*"
  to = "https://lukaskubiena.com/:splat"
  status = 301
  force = true

# Your existing redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 8888
  port = 8888
  publish = "."
  autoLaunch = true